// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0teDUXFpudk8UblUDUsPGOLzH_gIo2Pw',
    appId: '1:810739053255:web:00626219e20da247bc84e2',
    messagingSenderId: '810739053255',
    projectId: 'myth-1990',
    authDomain: 'myth-1990.firebaseapp.com',
    storageBucket: 'myth-1990.appspot.com',
    measurementId: 'G-EG0B0WFTXS',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcjZTw6qZVmJXlixQ1fBK5QYA-qzKFaF8',
    appId: '1:810739053255:android:b9cc835055470c1bbc84e2',
    messagingSenderId: '810739053255',
    projectId: 'myth-1990',
    storageBucket: 'myth-1990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwqRxIngzvdeBvJ9s4GEC82ptI57Q-Bc',
    appId: '1:810739053255:ios:3e253da0ddee3978bc84e2',
    messagingSenderId: '810739053255',
    projectId: 'myth-1990',
    storageBucket: 'myth-1990.appspot.com',
    iosClientId: '810739053255-6vtko3ui3ohapdooicssitqn69ss1l0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bigwheel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJwqRxIngzvdeBvJ9s4GEC82ptI57Q-Bc',
    appId: '1:810739053255:ios:3e253da0ddee3978bc84e2',
    messagingSenderId: '810739053255',
    projectId: 'myth-1990',
    storageBucket: 'myth-1990.appspot.com',
    iosClientId: '810739053255-6vtko3ui3ohapdooicssitqn69ss1l0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bigwheel',
  );
}
